### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ShimShtein** [crazymykl/flogger#3]
Using latest flogger, and got two issues:
I am getting the error from subject, but the flogger returns valid output:
### Flogger gem

``` sh
$ gem list flog

*** LOCAL GEMS ***

flog (4.4.0)
```
### Flog output

``` sh
$ cat app/services/classification/class_param.rb | flog -aqm
    45.0: flog total
    15.0: flog/method average

    31.0: Classification::ClassParam#enc   -:3
     9.3: Classification::ClassParam#hashed_class_parameters -:31
     4.7: Classification::ClassParam#class_parameters -:25
$ echo "$?"
0
```
## Standard error report

**Atom Version**: 1.8.0
**System**: "Fedora release
**Thrown From**: [flogger](https://github.com/crazymykl/flogger) package, v0.3.1
### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /home/shim/.atom/packages/flogger/lib/flog-adapter.coffee:7

TypeError: Cannot read property 'match' of undefined
    at parse (/home/shim/.atom/packages/flogger/lib/flog-adapter.coffee:7:29)
    at BufferedProcess.exit (/home/shim/.atom/packages/flogger/lib/flog-adapter.coffee:29:19)
    at triggerExitCallback (/usr/lib64/atom/src/buffered-process.js:215:47)
    at /usr/lib64/atom/src/buffered-process.js:222:18
    at Socket.<anonymous> (/usr/lib64/atom/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```
### Commands

```
     -0:03.8.0 command-palette:toggle (atom-text-editor.editor.is-focused.mini)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 flogger:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "goto",
      "symbols-view",
      "autocomplete-ctags",
      "atom-ctags"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      "tmp",
      ".tx",
      "locale",
      "log",
      "reports",
      ".*",
      "coverage",
      ".git/",
      "apipie-cache/",
      "tags",
      "fulltags"
    ],
    "packagesWithKeymapsDisabled": [
      "flogger"
    ],
    "projectHome": "~/Documents/my_proj"
  },
  "flogger": {
    "flogCommand": "/home/my_user/.rvm/gems/ruby-2.2.1@rails4/bin/flog",
    "highThreshold": 25,
    "mediumThreshold": 20
  }
}
```
### Installed Packages

``` coffee
# User
flogger, v0.3.1
language-plantuml, v0.2.0
last-cursor-position, v0.9.0
linter, v1.11.14
linter-erb, v1.0.2
linter-rubocop, v0.4.7
pigments, v0.31.2
plantuml-viewer, v0.7.0
project-manager, v2.9.7
tab-switcher, v1.5.3

# Dev
No dev packages
```

**Comment by crazymykl** [comment]
I am wondering if atom is invoking a different flog version, or has an incorrect path. That error would only occur if flog were getting back only one line of output.

**Comment by ShimShtein** [comment]
After a bit of hacking and trial and error, I remembered that I have patched the `flog-adapter.coffee` to ignore error codes.
After patching the adapter file a bit more, I was able to get the error out to console.

My problem was that I was using `rvm`, and in non-interactive shells it's disabled by default.
I fixed the issue by creating a small shell script that loaded `rvm` and invoked `flog`:

``` sh
#! /bin/sh

source $(/home/shim/.rvm/bin/rvm 2.2.1@rails4 do rvm env --path)

flog "$@"
```

Now everything works as a charm.
