### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by corincerami** [crazymykl/flogger#6]
This error happens when I attempt to use `crtl-f` in a certain source file.

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [flogger](https://github.com/crazymykl/flogger) package, v0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/ccerami/.atom/packages/flogger/lib/flog-adapter.coffee:13

TypeError: Cannot read property '0' of null
    at parse (/Users/ccerami/.atom/packages/flogger/lib/flog-adapter.coffee:13:6)
    at exit (/Users/ccerami/.atom/packages/flogger/lib/flog-adapter.coffee:33:19)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:299:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:312:11
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:181:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -1:28.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  3x -1:28.1.0 blur (input.hidden-input)
     -1:26.8.0 editor:consolidate-selections (input.hidden-input)
     -1:26.8.0 core:cancel (input.hidden-input)
  2x -1:26.8.0 blur (input.hidden-input)
     -1:26.5.0 editor:consolidate-selections (input.hidden-input)
     -1:26.5.0 core:cancel (input.hidden-input)
     -1:25.6.0 flogger:toggle (input.hidden-input)
 16x -1:22.7.0 blur (input.hidden-input)
     -1:03.3.0 flogger:toggle (input.hidden-input)
 26x -0:59.3.0 blur (input.hidden-input)
  3x -0:52.3.0 flogger:toggle (input.hidden-input)
 20x -0:47.2.0 blur (input.hidden-input)
  2x -0:07.2.0 flogger:toggle (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "elm-format"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "flogger": {
    "highThreshold": 30,
    "mediumThreshold": 15
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.17 (inactive)
atom-handlebars, v1.3.0 (active)
blame, v0.10.2 (inactive)
elm-format, v2.1.0 (inactive)
elmjutsu, v3.1.1 (active)
ember-snippets, v1.4.0 (active)
flogger, v0.3.3 (active)
language-babel, v2.51.0 (active)
language-elm, v1.5.0 (active)
language-haml, v0.24.1 (active)
language-rust, v0.4.9 (active)
linter, v1.11.21 (active)
linter-elm-make, v0.21.1 (active)
linter-ruby, v1.2.4 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (active)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by crazymykl** [comment]
Newer flog changed it's output format. Fixed in v0.3.5.
